### ISSUE TITLE
ModuleNotFoundError for cradle covariates

### ISSUE THREAD

**Issue by etiennejaussi** [ReddyLab/CRADLE#104]
Hello,

I am trying to run CRADLE for a STARR-seq experiment. I installed CRADLE with the pip command. I wrote a script for cradle covariates but I got the following error :

Traceback (most recent call last):
  File "/home/FCAM/ejaussi/miniconda/envs/cradle/bin/cradle", line 155, in <module>
    main()
  File "/home/FCAM/ejaussi/miniconda/envs/cradle/bin/cradle", line 150, in main
    from CRADLE.CalculateCovariates.covariates import run
  File "/home/FCAM/ejaussi/miniconda/envs/cradle/lib/python3.9/site-packages/CRADLE/CalculateCovariates/covariates.py", line 16, in <module>
    from CRADLE.CalculateCovariates.taskCovariates import calculateTaskCovariates
  File "CRADLE/CalculateCovariates/taskCovariates.pyx", line 12, in init CRADLE.CalculateCovariates.taskCovariates
**ModuleNotFoundError**: No module named 'CRADLE.CalculateCovariates.covariateUtils'

Do you know the source of this issue ?
Thank you in advance !
Etienne

**Comment by tncowart** [comment]
Hi Etienne,
Unfortunately I do not. Can you include the full command you ran that exited with this error? If you want to redact file names that's fine, I don't need to know them. I'd like to know all the command line options you used though.

Thank you,
Thomas

**Comment by etiennejaussi** [comment]
Thank you very much for your quick answer. Below is the script I use for this command :

#!/bin/bash

#SBATCH --job-name=calcov
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 6
#SBATCH --partition=general
#SBATCH --qos=general
#SBATCH --mail-type=END
#SBATCH --mem=30G
#SBATCH --mail-user=X
#SBATCH -o calcov_%j.out
#SBATCH -e calcov_%j.err

##########
# This script allows to calculate covariates
##########

# variables
genRef=/home/FCAM/ejaussi/CHIP_STARR_seq_CRADLE/genome_ref/hg19.2bit
peakRegions=/home/FCAM/ejaussi/CHIP_STARR_seq_run2/workflow/step10_chipseq_marks_and_peak_regions/data/sig_pos_interest_regions.bed
output=/home/FCAM/ejaussi/CHIP_STARR_seq_CRADLE_run2_test/calculates_covariate/output
gquadminus=/home/FCAM/ejaussi/CHIP_STARR_seq_CRADLE/data/gquad_files/GSE63874_Na_K_PDS_minus_hits_intersect_hg19_sorted_K.bw
gquadplus=/home/FCAM/ejaussi/CHIP_STARR_seq_CRADLE/data/gquad_files/GSE63874_Na_K_PDS_plus_hits_intersect_hg19_sorted_K.bw
mapFile=/home/FCAM/ejaussi/CHIP_STARR_seq_CRADLE/data/map_files/hg19_mappability_36mer.bw

source /home/FCAM/ejaussi/.bashrc
conda activate cradle

# run cradle covariates
cradle covariates \
	-l 300 \
	-r $peakRegions \
	-biasType shear pcr map gquad \
	-mapFile $mapFile \
	-gquadFile $gquadplus $gquadminus \
	-kmer 36 \
	-genome $genRef \
	-o $output/hg19_fragLen300_kmer36 \
	-p 12

**Comment by tncowart** [comment]
I haven't solved it yet, but I have recreated the issue. I'll keep working on it.

**Comment by tncowart** [comment]
I believe I fixed it. You can get an updated version (0.29.0) from pypi!

**Comment by etiennejaussi** [comment]
After updating, the script worked perfectly ! Thank you very much for fixing this issue, I can't wait to continue !

All the best,
Etienne
