### ISSUE TITLE
Possible typo and syntax error in CRADLE/CallPeak.callPeak.py

### ISSUE THREAD

**Issue by deeprob** [ReddyLab/CRADLE#91]
Hello, 
Thanks for developing CRADLE.
I think I found two minor bugs in the source code:

1. Syntax error in CRADLE/CallPeak/callPeak.py, line 181, `return minValue == 0 ? np.nan : np.round((-1) * np.log10(minValue), 2)` --> `np.nan if minValue == 0 else np.round((-1) * np.log10(minValue), 2)`
2. Typo in CRADLE/CallPeak/callPeak.py, line 184, `ctrlRC = [np.nanmean(np.array(bw.values(regionChromo, regionStart, regionEnd))) for bw in ctrlWB]`; variable `ctrlWB` --> `ctrlBW`

Also, wanted to let you know that pybigwig is throwing errors when the chromosomal coordinates are of type: `np.int`. I changed them to type `int` and it worked.

Thanks again,
Deepro

**Comment by tncowart** [comment]
Hi @deeprob -- Thank you! I apologize that I just saw this issue. I just pushed the fixes with 4b798c8.
  I'm curious about the `np.int` pybigwig issue though -- can you elaborate on how was that arising?
