### ISSUE TITLE
Update CRADLE in pypi to 0.26.1

### ISSUE THREAD

**Issue by tncowart** [ReddyLab/CRADLE#96]
@Young-Sook Can you update cradle to 0.26.1 on PyPI?

**Comment by Young-Sook** [comment]
I just updated CRADLE on PyPi. Do you mind if I add you as a collaborator in CRADLE on pypi so that you can update CRADLE on your own when I am not available?  If you don't mind, please let me know your user ID in Pypi. 

Thanks,
Young-Sook

**Comment by tncowart** [comment]
Thank you! My user id is "tncowart"

**Comment by Young-Sook** [comment]
just invited!

**Comment by tncowart** [comment]
I think you should make me a "maintainer" instead of an owner

**Comment by Young-Sook** [comment]
I just changed you to a maintainer.

**Comment by tncowart** [comment]
Thank you!
